### ISSUE TITLE
Launcher stays open when Foobar has successfully opened in Wine already.

### ISSUE THREAD

**Issue by ghost** [xeoron/foobar2000-mac#1]
This issue is self-explanatory, I fixed it by changing the "set ignoreErrors" line of the launcher app script to this:

set ignoreErrors to ">/dev/null 2>&1 &"

**Comment by xeoron** [comment]
Thank you.
Patch excepted, and code updated with credit see here:

https://github.com/xeoron/foobar2000-mac/blob/master/foobar2000Mac.applescript

Cheers,
-Jason

On Mon, Feb 3, 2014 at 6:34 PM, BoctorPoo notifications@github.com wrote:

> This issue is self-explanatory, I fixed it by changing the "set
> ignoreErrors" line of the launcher app script to this:
> 
> set ignoreErrors to ">/dev/null 2>&1 &"
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/xeoron/foobar2000-mac/issues/1
> .

## 

-Jason
