### ISSUE TITLE
 iPod/iPhone support ?

### ISSUE THREAD

**Issue by paines** [xeoron/foobar2000-mac#2]
This is more a question than issue: Will the iPod/Iphone syncing work thru Wine? 

This is a serious topic for me, cause I can't stand the way iTunes is managing syncing and would love to switch to something like foobar/clementine. Thanks!

**Comment by xeoron** [comment]
WINE is merely a Windows compatibility layer. If you want to sync using MS
Window tools, it may work. I don't have any iOS devices, so you will have
to test this yourself.

With that said, there are other programs for syncing ipod/iphone on the
Mac, such as iExplorer http://www.macroplant.com/iexplorer/

On Wed, Apr 23, 2014 at 7:15 AM, Anes Lihovac notifications@github.comwrote:

> This is more a question than issue: Will the iPod/Iphone syncing work thur
> Wine?
> 
> This is a serious topic for me, cause I can't stand the way iTunes is
> managing syncing and would love to switch to something like
> foobar/clementine. Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/xeoron/foobar2000-mac/issues/2
> .

## 

-Jason
